//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baballonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baballonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheek Expressions.
        /// </summary>
        public static string Calibration_Cheek_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Cheek_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Expressions.
        /// </summary>
        public static string Calibration_Eye_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents eyes from looking out in opposite directions, but may overcorrect..
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Description {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilize Eyes.
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Expressions.
        /// </summary>
        public static string Calibration_Jaw_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Jaw_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth Expressions.
        /// </summary>
        public static string Calibration_Mouth_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Mouth_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose Expressions.
        /// </summary>
        public static string Calibration_Nose_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Nose_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Maximums.
        /// </summary>
        public static string Calibration_Reset_Maximums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Maximums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Minimums.
        /// </summary>
        public static string Calibration_Reset_Minimums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Minimums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string Calibration_Title_Header {
            get {
                return ResourceManager.GetString("Calibration_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongue Expressions.
        /// </summary>
        public static string Calibration_Tongue_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Tongue_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing....
        /// </summary>
        public static string Common_Start_Typing {
            get {
                return ResourceManager.GetString("Common_Start_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle wired/wireless mode.
        /// </summary>
        public static string Firmware_Device_Configuration_Description {
            get {
                return ResourceManager.GetString("Firmware_Device_Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        public static string Firmware_Device_Configuration_Header {
            get {
                return ResourceManager.GetString("Firmware_Device_Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • After powering on/connecting your device you will have 20 seconds to press &quot;Refresh&quot; and select your device from the dropdown.
        /// </summary>
        public static string Firmware_Device_Instructions_1 {
            get {
                return ResourceManager.GetString("Firmware_Device_Instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Certain configuration operations will take a little bit!.
        /// </summary>
        public static string Firmware_Device_Instructions_2 {
            get {
                return ResourceManager.GetString("Firmware_Device_Instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle wired/wireless mode.
        /// </summary>
        public static string Firmware_Device_Mode_Header {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You WILL need to restart your tracker after changing the mode.
        /// </summary>
        public static string Firmware_Device_Mode_Instruction_1 {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Instruction_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You MAY need to restart the app after a flash for trackers to show.
        /// </summary>
        public static string Firmware_Device_Mode_Instruction_2 {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Instruction_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mode....
        /// </summary>
        public static string Firmware_Device_Mode_Select_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Select_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Firmware.
        /// </summary>
        public static string Firmware_Flashing_Button {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! You will need to restart your tracker.
        /// </summary>
        public static string Firmware_Flashing_Complete {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash your device&apos;s firmware.
        /// </summary>
        public static string Firmware_Flashing_Description {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing Options.
        /// </summary>
        public static string Firmware_Flashing_Header {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take around ~10 seconds. Don&apos;t leave this page!.
        /// </summary>
        public static string Firmware_Flashing_Note {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION!! THIS WILL FACTORY RESET YOUR TRACKER. YOU WILL NEED TO PERFORM A FIRST TIME SET UP AFTER FLASHING YOUR TRACKER..
        /// </summary>
        public static string Firmware_Flashing_Warning {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Mode.
        /// </summary>
        public static string Firmware_ModeSetButton_Default {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting mode.
        /// </summary>
        public static string Firmware_ModeSetButton_Setting {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set!.
        /// </summary>
        public static string Firmware_ModeSetButton_Success {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Devices.
        /// </summary>
        public static string Firmware_RefreshDevices_Default {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} device(s)..
        /// </summary>
        public static string Firmware_RefreshDevices_Found {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        public static string Firmware_RefreshDevices_Refreshing {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your tracker.
        /// </summary>
        public static string Firmware_Select_Tracker_Header {
            get {
                return ResourceManager.GetString("Firmware_Select_Tracker_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker connected!.
        /// </summary>
        public static string Firmware_SelectTracker_Connected {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tracker.
        /// </summary>
        public static string Firmware_SelectTracker_Default {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracker did not respond..
        /// </summary>
        public static string Firmware_SelectTracker_NoResponse {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string Firmware_Title_Header {
            get {
                return ResourceManager.GetString("Firmware_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see trackers....
        /// </summary>
        public static string Firmware_TrackerComboBox_Default {
            get {
                return ResourceManager.GetString("Firmware_TrackerComboBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Wifi and more.
        /// </summary>
        public static string Firmware_Wifi_Configuration_Description {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Configuration.
        /// </summary>
        public static string Firmware_Wifi_Configuration_Header {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your Wi-Fi credentials.
        /// </summary>
        public static string Firmware_Wifi_Credentials_Header {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Credentials_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • If you want to use your tracker wirelessly, you NEED to set its Wifi credentials.
        /// </summary>
        public static string Firmware_Wifi_Instructions_1 {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You MUST scan for Wifi networks BEFORE you can set your Wifi credentials.
        /// </summary>
        public static string Firmware_Wifi_Instructions_2 {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Password.
        /// </summary>
        public static string Firmware_Wifi_Password_Label {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter WiFi password....
        /// </summary>
        public static string Firmware_Wifi_Password_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Network Name (SSID).
        /// </summary>
        public static string Firmware_Wifi_SSID_Label {
            get {
                return ResourceManager.GetString("Firmware_Wifi_SSID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing to see WiFi networks....
        /// </summary>
        public static string Firmware_Wifi_SSID_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Wifi_SSID_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Wifi Networks.
        /// </summary>
        public static string Firmware_WifiScanButton_Default {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed. Click to try again..
        /// </summary>
        public static string Firmware_WifiScanButton_Error {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning. This will take at most 30 seconds.
        /// </summary>
        public static string Firmware_WifiScanButton_Scanning {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} networks. Click to scan again..
        /// </summary>
        public static string Firmware_WifiScanButton_Success {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Wifi Creds.
        /// </summary>
        public static string Firmware_WifiSetButton_Default {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string Firmware_WifiSetButton_Error {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting WiFi credentials.
        /// </summary>
        public static string Firmware_WifiSetButton_Setting {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent!.
        /// </summary>
        public static string Firmware_WifiSetButton_Success {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the brightness of the image.
        /// </summary>
        public static string Home_Cameras_Brightness_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Brightness.
        /// </summary>
        public static string Home_Cameras_Brightness_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropping.
        /// </summary>
        public static string Home_Cameras_Cropping_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Cropping_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the image horizontally.
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal flip.
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the image in a circle.
        /// </summary>
        public static string Home_Cameras_Rotation_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Rotation.
        /// </summary>
        public static string Home_Cameras_Rotation_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Camera.
        /// </summary>
        public static string Home_Cameras_Start_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Start_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Camera.
        /// </summary>
        public static string Home_Cameras_Stop_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Stop_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Home_Cameras_Tracking_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Tracking_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the image vertically.
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Flip.
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Calibration.
        /// </summary>
        public static string Home_Eye_Calibration {
            get {
                return ResourceManager.GetString("Home_Eye_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera Address.
        /// </summary>
        public static string Home_Face_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera.
        /// </summary>
        public static string Home_Face_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Face Frame.
        /// </summary>
        public static string Home_Face_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera Settings.
        /// </summary>
        public static string Home_Face_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Camera Address.
        /// </summary>
        public static string Home_Left_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye Camera.
        /// </summary>
        public static string Home_Left_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Left Frame.
        /// </summary>
        public static string Home_Left_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Camera Settings.
        /// </summary>
        public static string Home_Left_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Camera Address.
        /// </summary>
        public static string Home_Right_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye Camera.
        /// </summary>
        public static string Home_Right_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Right Frame.
        /// </summary>
        public static string Home_Right_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Camera Settings.
        /// </summary>
        public static string Home_Right_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title_Header {
            get {
                return ResourceManager.GetString("Home_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Settings_OSC_Description {
            get {
                return ResourceManager.GetString("Settings_OSC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Settings_OSC_Header {
            get {
                return ResourceManager.GetString("Settings_OSC_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDB.
        /// </summary>
        public static string Settings_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Settings_Theme_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
    }
}
