//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baballonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baballonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheek Expressions.
        /// </summary>
        public static string Calibration_Cheek_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Cheek_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Expressions.
        /// </summary>
        public static string Calibration_Eye_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents eyes from looking out in opposite directions, but may overcorrect..
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Description {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilize Eyes.
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Expressions.
        /// </summary>
        public static string Calibration_Jaw_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Jaw_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth Expressions.
        /// </summary>
        public static string Calibration_Mouth_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Mouth_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose Expressions.
        /// </summary>
        public static string Calibration_Nose_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Nose_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Maximums.
        /// </summary>
        public static string Calibration_Reset_Maximums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Maximums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Minimums.
        /// </summary>
        public static string Calibration_Reset_Minimums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Minimums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string Calibration_Title_Header {
            get {
                return ResourceManager.GetString("Calibration_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongue Expressions.
        /// </summary>
        public static string Calibration_Tongue_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Tongue_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing....
        /// </summary>
        public static string Common_Start_Typing {
            get {
                return ResourceManager.GetString("Common_Start_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the brightness of the image.
        /// </summary>
        public static string Home_Cameras_Brightness_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Brightness.
        /// </summary>
        public static string Home_Cameras_Brightness_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropping.
        /// </summary>
        public static string Home_Cameras_Cropping_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Cropping_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the image horizontally.
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal flip.
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the image in a circle.
        /// </summary>
        public static string Home_Cameras_Rotation_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Rotation.
        /// </summary>
        public static string Home_Cameras_Rotation_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Camera.
        /// </summary>
        public static string Home_Cameras_Start_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Start_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Camera.
        /// </summary>
        public static string Home_Cameras_Stop_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Stop_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Home_Cameras_Tracking_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Tracking_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the image vertically.
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Flip.
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Calibration.
        /// </summary>
        public static string Home_Eye_Calibration {
            get {
                return ResourceManager.GetString("Home_Eye_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera Address.
        /// </summary>
        public static string Home_Face_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera.
        /// </summary>
        public static string Home_Face_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Face Frame.
        /// </summary>
        public static string Home_Face_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera Settings.
        /// </summary>
        public static string Home_Face_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Camera Address.
        /// </summary>
        public static string Home_Left_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye Camera.
        /// </summary>
        public static string Home_Left_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Left Frame.
        /// </summary>
        public static string Home_Left_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Camera Settings.
        /// </summary>
        public static string Home_Left_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Camera Address.
        /// </summary>
        public static string Home_Right_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye Camera.
        /// </summary>
        public static string Home_Right_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Right Frame.
        /// </summary>
        public static string Home_Right_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Camera Settings.
        /// </summary>
        public static string Home_Right_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title_Header {
            get {
                return ResourceManager.GetString("Home_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Settings_OSC_Description {
            get {
                return ResourceManager.GetString("Settings_OSC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Settings_OSC_Header {
            get {
                return ResourceManager.GetString("Settings_OSC_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDB.
        /// </summary>
        public static string Settings_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Settings_Theme_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
    }
}
